options:
  logging: CLOUD_LOGGING_ONLY
  serviceAccount: projects/music-462705/serviceAccounts/music-streaming-service@music-462705.iam.gserviceaccount.com

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'music-backend',
           '--source', '.',
           '--region', 'asia-south2',
           '--platform', 'managed',
           '--allow-unauthenticated']
