options:
  logging: CLOUD_LOGGING_ONLY  # Required for logging

steps:
  # Step 1: Install dependencies (runs with Cloud Build default account)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Deploy to Cloud Run (uses your custom service account)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'music-backend',
           '--source', '.',
           '--region', 'asia-south2',
           '--platform', 'managed',
           '--allow-unauthenticated',
           '--service-account', 'music-streaming-service@music-462705.iam.gserviceaccount.com']  # <<-- Key change
