options:
  logging: CLOUD_LOGGING_ONLY  # <<-- This fixes the error

steps:
  # Build and deploy Node.js app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'music-backend',
           '--source', '.',
           '--region', 'asia-south2',
           '--platform', 'managed']
